version: "3.9"
services:
  lede-build:
    image: "bkt92/openwrt-lede-build-env"
    #build: ./lede-build
    volumes:
      - "./release:/openwrt/release"
      - "./config:/openwrt/config"
    environment:
      GITREPO: https://github.com/coolsnowwolf/lede
      CONFIG: cr660x.config